"use client"
import { createContext } from 'react';
import biotoon from "@/assets/technical/biotoon.jpg";
import techRelay from "@/assets/technical/tech_relay.jpg";
import pythonCodingChallenge from "@/assets/technical/python_coding_challenge.jpg";
import roboRace from "@/assets/technical/robo_race.jpg";
import pharmaNext from "@/assets/technical/pharmaNext.jpg";
import techDebate from "@/assets/technical/tech_debate.jpg";
import droneRace from "@/assets/technical/drone_race.jpg";
import foxtrotSolo from "@/assets/cultural/foxtrot_solo.jpg";
import foxtrotDuet from "@/assets/cultural/foxtrot_duet.jpg";
import foxtrotGroup from "@/assets/cultural/foxtrot_group.jpg";
import swarSangamSolo from "@/assets/cultural/swar_sangam_solo.jpg";
import swarSangamDuet from "@/assets/cultural/swar_sangam_duet.jpg";
import swarSangamGroup from "@/assets/cultural/swar_sangam_group.jpg";
import xtacy from "@/assets/creativity/xtacy.jpg";
import battleOfBands from "@/assets/cultural/battle_of_bands.jpg";
import rangmanch from "@/assets/cultural/rangmanch.jpg";
import spotlightShow from "@/assets/cultural/spotlight_show.jpg";
import artmania from "@/assets/creativity/artmania.jpg";
import cookNoFlame from "@/assets/creativity/cook_no_flame.jpg";
import liveSketching from "@/assets/creativity/live_sketching.jpg";
import pitchPerfect from "@/assets/creativity/pitch_perfect.jpg";
import blindfoldMakeup from "@/assets/creativity/blindfold_makeup.jpg";
import adMadShow from "@/assets/management/ad_mad_show.jpg";
import extempore from "@/assets/management/extempore.jpg";
import businessPlan from "@/assets/management/business_plan.jpg";
import businessQuiz from "@/assets/management/business_quiz.jpg";
import collageMaking from "@/assets/management/collage_making.jpg";

export const eventsDataContext = createContext();
export const EventsDataProvider = ({ children }) => {

    const activities = {
        technical: [
            {
                title: "Biotoon Event",
                description:
                    "Cartoon your way through biology! Unleash your creativity and turn everyday biological processes into fun, engaging stories and cartoons.",
                image: biotoon,
                date: "26 March 2025",
                time: "1:00 PM - 3:00 PM",
                venue: "Audi 4",
                teamSize: "1",
                prizes: "Winner: Rs. 1100, Runner-up: Rs. 500",
                evaluationScheme: "Creativity, Originality, Humor, Relevance to the topic",
                OC: "Mayur Rastogi",
                OCContact: "7037386808",
                EC: "Alishba Aqlim",
                ECContact: "8171407965",
                fees: 50,
            },
            {
                title: "Tech Relay",
                description:
                    "TechRelay is an exciting relay-style event where participants solve tech questions and pass the challenge to their teammates, testing speed, knowledge, and teamwork.",
                image: techRelay,
                date: "26 March 2025",
                time: "1:00 PM - 4:00 PM",
                venue: "Adjacent to Vishveshwarya block",
                teamSize: "2 - 3",
                prizes: "Winner: Rs. 1100, Runner-up: Rs. 500",
                evaluationScheme: "First to reach the final destination wins the race.",
                OC: "Mayur Rastogi",
                OCContact: "7037386808",
                EC: "Kartikey Sharma",
                ECContact: "8864997581",
                fees: 150,
            },
            {
                title: "Python Coding Challenge",
                description:
                    "Python Coding Challenge is a three-stage event where participants tackle code desecration, debug errors, and determine code outputs, testing their Python skills and problem-solving abilities.",
                image: pythonCodingChallenge,
                date: "27 March 2025",
                time: "10:00 AM - 3:00 PM",
                venue: "Raman Block (B4) 107",
                teamSize: "1",
                prizes: "Winner: Rs. 1100, Runner-up: Rs. 500",
                evaluationScheme: "The One with the best output wins the challenge.",
                OC: "Mayur Rastogi",
                OCContact: "7037386808",
                EC: "Kartikey Sharma",
                ECContact: "8864997581",
                fees: 50,
            },
            {
                title: "Robo Race",
                description:
                    "RoboRace is a thrilling competition where robots race using AI or remote control, testing speed, accuracy, and innovation. Popular in events like RoboCup , it showcases the future of smart machines in action!",
                image: roboRace,
                date: "27 March 2025",
                time: "10:00 AM - 4:00 PM",
                venue: "Volleyball ground",
                teamSize: "2 - 4",
                prizes: "Winner: Rs. 1500, 1st Runner-up: Rs. 1000, 2nd Runner-up: Rs. 500",
                evaluationScheme: "The robot that completes the track in the shortest time wins.",
                OC: "Mayur Rastogi",
                OCContact: "7037386808",
                EC: "Vishwajeet",
                ECContact: "9858568272",
                fees: 150,
            },
            {
                title: "PharmaNext",
                description:
                    "PharmaNext event is competitive platform designed to foster ground breaking advancements in Pharmaceutical Technology. The competition invites researchers, Startups to present innovative solutions in Formulation/ Cosmetics, Nutraceuticals, Analytics & Medical Devices. The participants will showcase their ideas to experts, gain mentorship and collaboration opportunities. The goal is to accelerate the development of novel technologies that improves healthcare outcomes.",
                image: pharmaNext,
                date: "27 March 2025",
                time: "10:00 AM - 4:00 PM",
                venue: "Expo Stalls",
                teamSize: "2 - 4",
                prizes: "Certificates and Prizes",
                evaluationScheme: "Project description video, Detailed proposal pitch video outlining the problem, solution, impact.",
                OC: "Mayur Rastogi",
                OCContact: "7037386808",
                EC: "Arsha Mittal",
                ECContact: "8882461539",
                fees: 150,
            },
            {
                title: "Tech Debate",
                description:
                    "Tech Debate is a dynamic event where teams discuss and debate the pros and cons of trending technology topics, promoting critical thinking and diverse perspectives.",
                image: techDebate,
                date: "28 March 2025",
                time: "11:00 AM - 1:00 PM",
                venue: "Idea Lab",
                teamSize: "2",
                prizes: "Winner: Rs. 1100, Runner-up: Rs. 500",
                evaluationScheme: "Fluency, Facts and Figures, Communication skills, Active Listening",
                OC: "Mayur Rastogi",
                OCContact: "7037386808",
                EC: "Kartikey Sharma",
                ECContact: "8864997581",
                fees: 100,
            },
            {
                title: "Drone Race",
                description:
                    "Drone Race is an exciting competition where drones, controlled by AI or pilots, fly through tricky tracks at high speed. It tests skill, precision, and technology, making it a fun way to explore the future of flying robots!",
                image: droneRace,
                date: "28 March 2025",
                time: "10:00 AM - 1:00 PM",
                venue: "Volleyball Ground",
                teamSize: "2 - 4",
                prizes: "Winner: Rs. 2000, Runner-up: Rs. 1000",
                evaluationScheme: "The drone that completes the track in the shortest time wins.",
                OC: "Mayur Rastogi",
                OCContact: "7037386808",
                EC: "Shantanu",
                ECContact: "9027308517",
                fees: 150,
            },
        ],
        cultural: [
            {
                title: "Foxtrot Solo - Day 1",
                description:
                    "Step into rhythm, glide with grace—Foxtrot is not just a dance, it's a story in motion! Whether you own the stage solo, flow in a duet, or shine in a group, let the music lead you!",
                image: foxtrotSolo,
                date: "26 March 2025",
                time: "2:10 PM - 3:10 PM",
                venue: "Main Stage",
                teamSize: "1",
                prizes: "Winner: Rs. 1100, 1st/2nd Runner-up: Rs. 500",
                evaluationScheme: "Choreography and Creativity, Expression and Performance, Overall Impression, Theme, Formations, Rhythm and Timing, Dressing Style",
                OC: "Mahi",
                OCContact: "8700467603",
                EC: "Chetan Kumar",
                ECContact: "8439099891",
                fees: 50,
            },
            {
                title: "Foxtrot Duet - Day 2",
                description:
                    "Step into rhythm, glide with grace—Foxtrot is not just a dance, it's a story in motion! Whether you own the stage solo, flow in a duet, or shine in a group, let the music lead you!",
                image: foxtrotDuet,
                date: "27 March 2025",
                time: "11:00 AM - 12:00 PM",
                venue: "Main Stage",
                teamSize: "2",
                prizes: "Winner: Rs. 1100, 1st/2nd Runner-up: Rs. 500",
                evaluationScheme: "Choreography and Creativity, Expression and Performance, Overall Impression, Theme, Formations, Rhythm and Timing, Dressing Style",
                OC: "Mahi",
                OCContact: "8700467603",
                EC: "Chetan Kumar",
                ECContact: "8439099891",
                fees: 100,
            },
            {
                title: "Foxtrot Group - Day 2",
                description:
                    "Step into rhythm, glide with grace—Foxtrot is not just a dance, it's a story in motion! Whether you own the stage solo, flow in a duet, or shine in a group, let the music lead you!",
                image: foxtrotGroup,
                date: "27 March 2025",
                time: "3:00 PM - 5:00 PM",
                venue: "Main Stage",
                teamSize: "Min 6",
                prizes: "Winner: Rs. 8100, 1st Runner-up: Rs. 4100, 2nd Runner-up: Rs. 2100",
                evaluationScheme: "Choreography and Creativity, Expression and Performance, Overall Impression, Theme, Formations, Rhythm and Timing, Dressing Style",
                OC: "Mahi",
                OCContact: "8700467603",
                EC: "Chetan Kumar",
                ECContact: "8439099891",
                fees: 350,
            },
            {
                title: "Swar Sangam Solo",
                description:
                    "Swar Sangam—where every note finds its soul! Whether you mesmerize the stage solo or create magic in a duo and group, let your voice echo with passion and melody. Step up, sing out, and let music unite us!",
                image: swarSangamSolo,
                date: "26 March 2025",
                time: "11:00 AM - 12:00 PM",
                venue: "Main Stage",
                teamSize: "1",
                prizes: "Winner: Rs. 1100, 1st/2nd Runner-up: Rs. 500",
                evaluationScheme: "Vocal Technique, Stage Presence, Uniqueness, Artistic Identity, Memorability",
                OC: "Mahi",
                OCContact: "8700467603",
                EC: "Nikshy Goliyan",
                ECContact: "7668772059",
                fees: 50,
            },
            {
                title: "Swar Sangam Duet",
                description:
                    "Swar Sangam—where every note finds its soul! Whether you mesmerize the stage solo or create magic in a duo and group, let your voice echo with passion and melody. Step up, sing out, and let music unite us!",
                image: swarSangamDuet,
                date: "26 March 2025",
                time: "12:30 PM - 2:00 PM",
                venue: "Main Stage",
                teamSize: "2",
                prizes: "Winner: Rs. 1100, 1st/2nd Runner-up: Rs. 500",
                evaluationScheme: "Vocal Technique, Stage Presence, Uniqueness, Artistic Identity, Memorability",
                OC: "Mahi",
                OCContact: "8700467603",
                EC: "Nikshy Goliyan",
                ECContact: "7668772059",
                fees: 100,
            },
            {
                title: "Swar Sangam Group",
                description:
                    "Swar Sangam—where every note finds its soul! Whether you mesmerize the stage solo or create magic in a duo and group, let your voice echo with passion and melody. Step up, sing out, and let music unite us!",
                image: swarSangamGroup,
                date: "26 March 2025",
                time: "3:20 PM - 4:00 PM",
                venue: "Main Stage",
                teamSize: "Min 4",
                prizes: "Winner: Rs. 5100, 1st Runner-up: Rs. 3100, 2nd Runner-up: Rs. 2100",
                evaluationScheme: "Vocal Technique, Stage Presence, Uniqueness, Artistic Identity, Memorability",
                OC: "Mahi",
                OCContact: "8700467603",
                EC: "Nikshy Goliyan",
                ECContact: "7668772059",
                fees: 200,
            },
            {
                title: "Rangmanch - Skit/Nukkad Natak",
                description: "Rangmanch – Where stories come alive! Raise your voice, ignite emotions, and let the stage be your canvas. Whether it's a powerful skit or a gripping nukkad natak, captivate the audience and make an impact that lasts!",
                image: rangmanch,
                date: "28 March 2025",
                time: "11:00 AM - 1:00 PM",
                venue: "Main Stage",
                teamSize: "Min 6",
                prizes: "Winner: Rs. 5100, 1st Runner-up: Rs. 3100, 2nd Runner-up: Rs. 2100",
                evaluationScheme: "Stage Presence, Theme, Expression and Performance, Acting Skills, Script, Creativity, Costumes, Message and Impact",
                OC: "Mahi",
                OCContact: "8700467603",
                EC: "Shivansh Saini",
                ECContact: "7520271225",
                fees: 200,
            },
            {
                title: "Battle of Bands",
                description:
                    "Battle of Bands – Where rhythm meets rivalry. Unleash electrifying energy, blend melodies with madness, and let your band set the stage on fire. Compete, conquer, and let the music decide the ultimate champion!",
                image: battleOfBands,
                date: "27 March 2025",
                time: "12:00 PM - 3:00 PM",
                venue: "Main Stage",
                teamSize: "Min 4",
                prizes: "Winner: Rs. 11000, 1st Runner-up: Rs. 5100, 2nd Runner-up: Rs. 2100",
                evaluationScheme: "Stage Presence, Harmony and Synchronization, Crowd Engagement, Vocal Technique, Uniqueness",
                OC: "Mahi",
                OCContact: "8700467603",
                EC: "Mayank Tamta",
                ECContact: "8923166035",
                fees: 350,
            },
            {
                title: "Spotlight show - Open Mic",
                description:
                    "Spotlight Show – Where every voice matters! Step into the light, share your stories, poetry, music, or comedy, and let your words leave a mark. The stage is yours—own it, express it, and shine!",
                image: spotlightShow,
                date: "28 March 2025",
                time: "3:00 PM - 4:00 PM",
                venue: "Main Stage",
                teamSize: "Min 1",
                prizes: "Gift Hampers",
                evaluationScheme: "Stage Presence, Crowd Engagement, Message Delivery, Entertainment",
                OC: "Mahi",
                OCContact: "8700467603",
                EC: "Rajnandni",
                ECContact: "7006013317",
                fees: 0,
            },
        ],
        creativity: [
            {
                title: "Xtacy - The Fashion Show",
                description:
                    "Xtacy – The Ultimate Runway Affair! Step into the spotlight, where fashion meets passion and confidence becomes couture. Own the stage, redefine elegance, and let your style leave an unforgettable mark!",
                image: xtacy,
                date: "26 March 2025",
                time: "4:30 PM - 7:00 PM",
                venue: "Main Stage",
                teamSize: "1",
                prizes: "Certificates and Tags",
                evaluationScheme: "Costume & Styling, Walk & Stage Presence, Concept & Theme Representation, Expressions & Attitude, Overall Impact & X-Factor",
                OC: "Kashish Sharma",
                OCContact: "9258817121",
                EC: "Tanisha Sharma",
                ECContact: "9027557677",
                fees: 0,
            },
            {
                title: "Cook-No-Flame",
                description:
                    "Cook-No-Flame is a fun and creative event where participants prepare delicious dishes without using fire, testing their culinary skills and creativity.",
                image: cookNoFlame,
                date: "26 March 2025",
                time: "1:00 PM - 3:00 PM",
                venue: "Raman Block basement",
                teamSize: "1 - 2",
                prizes: "Winner: Rs. 1500, 1st Runner-up: Rs. 1100, 2nd Runner-up: Rs. 500",
                evaluationScheme: "Taste, Presentation, Creativity",
                OC: "Kashish Sharma",
                OCContact: "9258817121",
                EC: "Vanshika Vashishth",
                ECContact: "7217325226",
                fees: 80,
            },
            {
                title: "Live Sketching",
                description:
                    "Participants are required to click the picture of their desired location or scenery and then draw it on the provided A3 sheet.",
                image: liveSketching,
                date: "26 March 2025",
                time: "2:00 PM - 4:00 PM",
                venue: "AICTE Idea Lab",
                teamSize: "1",
                prizes: "Winner: Rs. 1100, 1st Runner-up: Rs. 500, 2nd Runner-up: Rs. 250",
                evaluationScheme: "Realism, Creativity, Composition, Technique, Overall Presentation",
                OC: "Kashish Sharma",
                OCContact: "9258817121",
                EC: "Vishal Jain",
                ECContact: "6397151942",
                fees: 50,
            },
            {
                title: "Pitch perfect",
                description:
                    "Students will be asked to pitch about their Idea in the first round and then for the second round the team will provide them the topic about which they will have to pitch.",
                image: pitchPerfect,
                date: "27 March 2025",
                time: "10:00 AM - 4:00 PM",
                venue: "AICTE Idea Lab",
                teamSize: "1 - 3",
                prizes: "Winner: 2100, 1st Runner-up: 1100, 2nd Runner-up: 500",
                evaluationScheme: "Business Idea, Presentation, Communication Skills, Clarity of Thought, Relevance to the Topic",
                OC: "Kashish Sharma",
                OCContact: "9258817121",
                EC: "Stuti Kumar",
                ECContact: "7906274257",
                fees: 150,
            },
            {
                title: "Blindfold Makeup",
                description:
                    "Participant are required to bring the partner whom they would apply makeup while being blindfolded.",
                image: blindfoldMakeup,
                date: "28 March 2025",
                time: "10:00 AM - 12:00 PM",
                venue: "Ground opp. to Boys Hostel 2",
                teamSize: "2",
                prizes: "Winner: Rs. 1500, 1st Runner-up: Rs. 1100, 2nd Runner-up: Rs. 500",
                evaluationScheme: "Creativity and Acccuracy of Makeup",
                OC: "Kashish Sharma",
                OCContact: "9258817121",
                EC: "Lucky Tomar",
                ECContact: "9193107757",
                fees: 100,
            },
            {
                title: "Artmania - Wall Painting",
                description:
                    "Art Mania – Where Walls Speak Creativity! Unleash your imagination, let colors dance, and turn blank walls into masterpieces. Every stroke tells a story—paint your vision, leave your mark!",
                image: artmania,
                date: "26 March 2025",
                time: "9:30 AM - 5:00 PM ",
                venue: "Canteen Wall",
                teamSize: "2 - 3",
                prizes: "Winner: Rs. 1100",
                evaluationScheme: "Creativity & Originality, Theme Relevance, Technique & Skil, Composition & Aesthetic Appeal, Overall Presentation & ImpacT",
                OC: "Kashish Sharma",
                OCContact: "9258817121",
                EC: "Vipanshi Kundral",
                ECContact: "7051158951",
                fees: 50,
            },
        ],
        management: [
            {
                title: "Ad-Mad Show",
                description:
                    "An Ad Mad Competition is a fun and creative event where participants create and present advertisements for products or services.",
                image: adMadShow,
                date: "26 March 2025",
                time: "10:00 AM - 11:30 AM",
                venue: "Audi 6",
                teamSize: "4 - 6",
                prizes: "Winner: 1100, 1st Runner-up: 500",
                evaluationScheme: "Creativity and Presentation",
                OC: "Kanak Sharma",
                OCContact: "7983056642",
                EC: "Sarthak",
                ECContact: "7302672818",
                fees: 200,
            },
            {
                title: "Extempore",
                description:
                    "To test and develop a participant's ability to think and speak on a given topic spontaneously and coherently.",
                image: extempore,
                date: "26 March 2025",
                time: "12:00 AM - 1:30 PM",
                venue: "Audi 6",
                teamSize: "1",
                prizes: "Winner: 1100, 1st Runner-up: 500",
                evaluationScheme: "Focus on the topic, Content, Fluency, Clarity, Confidence, Time Management",
                OC: "Kanak Sharma",
                OCContact: "7983056642",
                EC: "Akash Tomar",
                ECContact: "8395059673",
                fees: 50,
            },
            {
                title: "Business Plan",
                description:
                    "To provide a platform for participants to present their business ideas and plans to a panel of judges.",
                image: businessPlan,
                date: "26 March 2025",
                time: "2:00 PM - 4:00 PM",
                venue: "Audi 6",
                teamSize: "2 - 5",
                prizes: "Winner: 1100, 1st Runner-up: 500",
                evaluationScheme: "Financial Viability, Innovation, Feasibility, Presentation",
                OC: "Kanak Sharma",
                OCContact: "7983056642",
                EC: "Mukul Sharma",
                ECContact: "7037733688",
                fees: 150,
            },
            {
                title: "Business Quiz",
                description:
                    "To assess and enhance participants knowledge and understanding of various business concepts, practices, and real-world applications.",
                image: businessQuiz,
                date: "27 March 2025",
                time: "10:00 AM - 11:30 AM",
                venue: "Audi 6",
                teamSize: "2 - 4",
                prizes: "Winner: 1100, 1st Runner-up: 500",
                evaluationScheme: "Assessment of Business Knowledge, Analytical Skills, Problem Solving, Teamwork",
                OC: "Kanak Sharma",
                OCContact: "7983056642",
                EC: "Abhishek Singh",
                ECContact: "9058285845",
                fees: 150,
            },
            {
                title: "Collage Making",
                description:
                    "To provide a creative platform for individuals to express their ideas, emotions, or concepts by assembling different materials, images, or objects.",
                image: collageMaking,
                date: "27 March 2025",
                time: "12:00 PM - 2:00 PM",
                venue: "Audi 6",
                teamSize: "3 - 4",
                prizes: "Winner: 1100, 1st Runner-up: 500",
                evaluationScheme: "Relevance to the Theme, Creativity, Originality, Presentation",
                OC: "Kanak Sharma",
                OCContact: "7983056642",
                EC: "Megha Singh",
                ECContact: "7455988843",
                fees: 150,
            },
        ],
    };

    return (
        <eventsDataContext.Provider value={{ activities }}>
            {children}
        </eventsDataContext.Provider>
    );
};